import {rooms,items,endings,SAVE_KEY,initialState,restoreState,inspect,collect,solve,travel,chooseEnding} from './engine.js';
import {isChallengeComplete,startChallenge,resetChallenges} from './challenges.js';
import {createSoundtrack} from './soundtrack.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const paths={book:'M4 4h6a3 3 0 0 1 3 3v14a4 4 0 0 0-4-2H4z M22 4h-6a3 3 0 0 0-3 3v14a4 4 0 0 1 4-2h5z',scroll:'M7 4h12v14a3 3 0 0 1-3 3H5a3 3 0 0 1-3-3v-2h12v2a2 2 0 0 0 4 0 M7 4a3 3 0 0 0-6 0v2h6v10 M10 8h6 M10 12h6',clock:'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18 M12 6v6l4 2 M10 1h4',lock:'M7 11V7a5 5 0 0 1 10 0v4 M5 11h14v11H5z M12 15v3',gear:'m9 3 1-2h4l1 2 3 1 2-1 2 4-2 2v4l2 2-2 4-2-1-3 1-1 2h-4l-1-2-3-1-2 1-2-4 2-2V9L2 7l2-4 2 1z M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8',apple:'M12 7c-6-4-11 2-9 8 2 7 5 8 9 6 4 2 7 1 9-6 2-6-3-12-9-8z M12 7V4l3-3 M13 4c3 0 5-1 5-3-3 0-5 1-5 3',gem:'m12 2 9 9-9 11-9-11z M3 11h18 M12 2l-4 9 4 11 4-11z',key:'M8 3a5 5 0 1 0 0 10 5 5 0 0 0 0-10 M11 11l10 10 M16 16l3-3 M18 18l3-3',mirror:'M12 2c-5 0-8 4-8 9s3 9 8 9 8-4 8-9-3-9-8-9z M9 23h6 M12 20v3 M14 5l-5 7h6l-4 5',sound:'M3 9h4l5-4v14l-5-4H3z M16 8c3 2 3 6 0 8 M19 5c5 4 5 10 0 14',mute:'M3 9h4l5-4v14l-5-4H3z M17 9l5 6 M22 9l-5 6'};
const icon=(name)=>`<svg viewBox="0 0 26 26" fill="none" stroke="currentColor" stroke-width="1.3" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name]||paths.gem}"/></svg>`;
let state;try{state=restoreState(localStorage.getItem(SAVE_KEY))}catch{state=initialState()}
let view='home',lastFocus=null,toastTimeout,audio=null,activeNodes=[],saveFailed=false;
const soundtrack=createSoundtrack();
const currentTrack=()=>view==='home'?'home':view==='ending'?(state.ending||'dawn'):rooms[state.room].id;
const save=()=>{try{localStorage.setItem(SAVE_KEY,JSON.stringify(state));saveFailed=false}catch{saveFailed=true}$('#save-indicator').textContent=saveFailed?'◇ 無法存檔；請保持本頁開啟':'◇ 進度已儲存在此裝置';};
const formatTime=n=>`${String(Math.floor(n/60)).padStart(2,'0')}:${String(Math.floor(n%60)).padStart(2,'0')}`;
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('visible');clearTimeout(toastTimeout);toastTimeout=setTimeout(()=>$('#toast').classList.remove('visible'),3200)}
function modal(title,eyebrow,html){const d=$('#modal');if(!d.open)lastFocus=document.activeElement;$('#modal-title').textContent=title;$('#modal-eyebrow').textContent=eyebrow;$('#modal-body').innerHTML=html;if(!d.open)d.showModal();d.scrollTop=0;}
function closeModal(){$('#modal').close();if(lastFocus?.isConnected)lastFocus.focus()}
$('#modal-close').onclick=closeModal;
$('#modal').addEventListener('click',e=>{if(e.target===$('#modal')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeModal()}});
$('#modal').addEventListener('close',()=>{if(lastFocus?.isConnected)lastFocus.focus()});
function showView(next){if($('#modal').open)closeModal();view=next;['home','game','ending'].forEach(id=>$('#'+id).classList.toggle('hidden',id!==next));$('#main').classList.remove('view-enter');void $('#main').offsetWidth;$('#main').classList.add('view-enter');window.scrollTo({top:0,behavior:'instant'});if(next==='game')renderGame();if(next==='home')renderHome();if(next==='ending')renderEnding();soundtrack.select(currentTrack());}
function renderHome(){const hasSave=state.started;$('#continue').classList.toggle('hidden',!hasSave);$('#start').textContent=hasSave?'開始新旅程 ⟶':'踏入魔鏡 ⟶';$('#chapter-cards').innerHTML=rooms.map((r,i)=>`<button class="chapter-card" data-chapter="${i}" aria-label="${r.chapter} ${r.title}，${i<=state.unlocked?'可探索':'尚未解鎖'}"><img class="card-image" loading="lazy" src="assets/${r.image}" alt=""><span class="card-number">0${i+1}</span><span class="card-status">${icon(state.solved.includes(i)?'gem':i<=state.unlocked?'mirror':'lock')}${state.solved.includes(i)?'已解開':i<=state.unlocked?'可探索':'封印中'}</span><h3>${r.title}</h3><p>${r.subtitle}</p><span class="card-arrow">⟶</span></button>`).join('');$$('[data-chapter]').forEach(el=>el.onclick=()=>{const i=Number(el.dataset.chapter);if(i>state.unlocked){toast('這道門仍被封印。先完成前面的章節。');return}state.started=true;state.ending=null;travel(state,i);save();showView('game');});}
function renderGame(){const r=rooms[state.room],done=state.solved.includes(state.room);soundtrack.select(r.id);$('#room-chapter').textContent=r.chapter;$('#room-title').textContent=r.title;$('#scene-subtitle').textContent=r.subtitle;$('#scene').className='scene '+r.atmosphere;$('#scene-image').src='assets/'+r.image;$('#scene-image').alt=r.title+'的探索場景';$('#objective').textContent=done?'封印已解開。妳可以重看線索，或前往下一幕。':r.objective;$('#narrative').textContent=done?r.unlock:r.intro;$('#timer').textContent=formatTime(state.elapsed);$('#hotspots').innerHTML=r.spots.map(s=>`<button class="hotspot ${s.lock?'seal':''} ${state.seen.includes(s.id)?'seen':''}" style="left:${s.x}%;top:${s.y}%" data-spot="${s.id}" aria-label="${s.label}${state.seen.includes(s.id)?'，已查看':''}">${icon(s.icon)}<span>${s.label}</span></button>`).join('');$$('[data-spot]').forEach(b=>b.onclick=()=>openSpot(b.dataset.spot));$('#scene-progress').textContent=`已探索 ${r.spots.filter(s=>!s.lock&&state.seen.includes(s.id)).length} / 3 處線索 · 真相 ${state.solved.length} / 5`;$('#room-next').classList.toggle('hidden',!done);$('#room-puzzle').classList.toggle('hidden',done);$('#room-next').textContent=state.room===4?'決定最後的代價 ⟶':'走向下一扇門 ⟶';$('#room-puzzle').onclick=openPuzzle;$('#room-next').onclick=()=>{if(state.room===4){openFate();return}travel(state,state.room+1);save();renderGame();window.scrollTo({top:0,behavior:'instant'});toast('新的場景已解鎖');};$('#room-tabs').innerHTML=rooms.map((x,i)=>`<button ${i>state.unlocked?'disabled':''} class="${i===state.room?'active':''}" data-room="${i}" ${i===state.room?'aria-current="step"':''}><span>0${i+1} ${i>state.unlocked?'· 封印':''}</span>${x.title}</button>`).join('');$$('[data-room]').forEach(b=>b.onclick=()=>{travel(state,Number(b.dataset.room));save();renderGame()});renderInventory();$('#journal-count').textContent=state.seen.length;save();}
function renderInventory(){$('#inventory-count').textContent=state.inventory.length+' 件';$('#inventory').innerHTML=state.inventory.length?state.inventory.map(id=>`<button data-item="${id}" aria-label="檢視${items[id].name}">${icon(items[id].icon)}<span>${items[id].name}</span></button>`).join(''):'<p class="inventory-empty">空蕩蕩的口袋，等待第一條線索。</p>';$$('[data-item]').forEach(b=>b.onclick=()=>{const it=items[b.dataset.item];modal(it.name,'INVENTORY · 隨身物品',`<div class="modal-image-icon">${icon(it.icon)}</div><p class="modal-text">${it.text}</p><button class="secondary-button" id="item-back">返回探索</button>`);$('#item-back').onclick=closeModal;});}
function openSpot(id){const spot=inspect(state,id);if(!spot)return;if(spot.lock){openPuzzle();return}save();renderGame();const has=spot.item&&state.inventory.includes(spot.item);modal(spot.label,'DISCOVERY · 發現',`<div class="modal-image-icon">${icon(spot.icon)}</div><p class="modal-text">${spot.text}</p>${spot.item?`<button class="primary-button" id="take-item" ${has?'disabled':''}>${has?'已放入隨身物品':'收取'+spot.itemName+' ＋'}</button>`:''}<p class="modal-note">這段線索已記錄在妳的筆記中。</p>`);if(spot.item&&!has)$('#take-item').onclick=()=>{collect(state,id);save();renderGame();closeModal();playCue('collect');toast(spot.itemName+' 已收入隨身物品');};}
function attempt(answer){const result=solve(state,answer);if(!result.ok){playCue('wrong');if(result.reason==='item')$('#feedback').textContent='妳還缺少'+items[result.item].name+'。先在房間裡找到並收取它。';else $('#feedback').textContent='封印沒有回應。重新檢視線索，再試一次。';return false;}save();renderGame();playCue('solve');const r=rooms[state.room];modal('封印已解開','TRUTH FRAGMENT · '+r.reward,`<div class="success-gem">◇</div><p class="modal-text">${r.unlock}</p><p class="modal-note">真相碎片 ${state.solved.length} / 5${state.room===1?' · 工程藍圖已收入隨身物品':''}</p><button class="primary-button" id="success-next">${state.room===4?'面對最後的交易':'進入下一幕'} ⟶</button><button class="secondary-button" id="success-stay">留在此處探索</button>`);$('#success-next').onclick=()=>{closeModal();if(state.room===4)openFate();else{travel(state,state.room+1);save();renderGame();window.scrollTo({top:0,behavior:'instant'});}};$('#success-stay').onclick=closeModal;return true;}
function openPuzzle(){const r=rooms[state.room];if(state.solved.includes(state.room)){if(state.room===4)openFate();else{modal('這道封印已經解開',r.chapter,`<p class="modal-text">${r.unlock}</p><button id="solved-close" class="primary-button">繼續探索</button>`);$('#solved-close').onclick=closeModal;}return;}
 if(!isChallengeComplete(r.id)){startChallenge(r.id,{modal,playCue,success:()=>{toast('互動謎題已完成，封印的第二層正在開啟。');openPuzzle()}});return;}
 const prerequisite=r.requires&&!state.inventory.includes(r.requires)?`<p class="modal-note">需要物品：${items[r.requires].name}。妳可以先檢視謎題。</p>`:'';
 if(r.puzzle==='code'){modal('禁書櫃的密碼','THE SEAL · 四位數字',`<p class="modal-text">錶蓋提醒妳：「先是禁忌鐘聲，後是出生的代價。」</p>${prerequisite}<form id="code-form" class="puzzle-form"><label for="code">轉動四個刻度</label><input id="code" class="code-input" inputmode="numeric" pattern="[0-9]{4}" autocomplete="off" maxlength="4" placeholder="· · · ·" aria-describedby="feedback" required><p id="feedback" class="puzzle-feedback" role="status"></p><button class="primary-button" type="submit">解開封印 ⟶</button></form>`);$('#code-form').onsubmit=e=>{e.preventDefault();attempt($('#code').value)};$('#code')?.focus({preventScroll:true});return;}
 if(r.puzzle==='sequence'){let seq=[];modal(r.id==='mine'?'讓城市重新溫暖':'通往鏡界的符印','THE SEAL · 排列順序',`<p class="modal-text">${r.id==='mine'?'依工程手札依序開啟三道閥門。':'依照咒書的三句話，依序觸碰符印。'}</p>${prerequisite}<div id="sequence" class="sequence-display" aria-live="polite"></div><div class="puzzle-options">${r.options.map(o=>`<button data-option="${o.id}"><span>${o.symbol}</span>${o.label}</button>`).join('')}</div><p id="feedback" class="puzzle-feedback" role="status"></p><button id="submit-seq" class="primary-button" disabled>確認順序 ⟶</button><button id="clear-seq" class="secondary-button">重新排列</button>`);const update=()=>{$('#sequence').innerHTML=[0,1,2].map(i=>`<span>${seq[i]?r.options.find(o=>o.id===seq[i]).label:'0'+(i+1)}</span>`).join('');$('#submit-seq').disabled=seq.length!==3;$$('[data-option]').forEach(b=>b.disabled=seq.includes(b.dataset.option));};$$('[data-option]').forEach(b=>b.onclick=()=>{if(seq.length<3&&!seq.includes(b.dataset.option)){seq.push(b.dataset.option);update();playCue('click')}});$('#clear-seq').onclick=()=>{seq=[];$('#feedback').textContent='';update()};$('#submit-seq').onclick=()=>attempt(seq);update();return;}
 if(r.puzzle==='questions'){let answers=[];const draw=()=>{const q=r.questions[answers.length];modal('王后的三個問題','THE SEAL · '+(answers.length+1)+' / 3',`${prerequisite}<p class="question-progress">QUESTION 0${answers.length+1}</p><p class="question-text">${q.text}</p>${q.options.map(o=>`<button class="choice-option" data-answer="${o.id}">${o.label} <span>⟶</span></button>`).join('')}<p id="feedback" class="puzzle-feedback" role="status"></p><button id="questions-reset" class="secondary-button">回到第一問</button>`);$$('[data-answer]').forEach(b=>b.onclick=()=>{answers.push(b.dataset.answer);if(answers.length===3){if(!attempt(answers)){answers=[];$('#questions-reset').textContent='重新回答三個問題';$$('[data-answer]').forEach(x=>x.disabled=true)}}else draw()});$('#questions-reset').onclick=()=>{answers=[];draw()};};draw();return;}
 modal('最後的血脈繼承人','THE SEAL · 王冠契約',`<p class="modal-text">魔鏡問：「誰的名字，仍讓王國的生命抵押繼續？」</p>${r.options.map(o=>`<button class="choice-option" data-name="${o.id}">${o.label} <span>⟶</span></button>`).join('')}<p id="feedback" class="puzzle-feedback" role="status"></p>`);$$('[data-name]').forEach(b=>b.onclick=()=>attempt(b.dataset.name));
}
function openFate(){if(state.solved.length<5)return;modal('妳願意支付什麼？','THE LAST CHOICE · 最後的代價',`<p class="modal-text">妳已握住五份真相。放棄名字，生命抵押將終止；但結界也會消失。\n\n赫索的工程藍圖仍在妳手中。這一次，妳可以尋找第三種方法。</p><button class="choice-option" data-fate="dawn">先完成蒸汽工程，再交出名字<small>讓工程替代結界。世界獲救，但所有人將忘記妳。</small></button><button class="choice-option" data-fate="frost">立刻交出名字，解除所有抵押<small>生命重獲自由。尚未準備好的城市將面對霜潮。</small></button><button class="choice-option" data-fate="crown">保住名字，繼承血色王冠<small>妳仍被世界記住。生命交易也將繼續。</small></button><p class="modal-note">這個選擇會決定結局。完成後可回來探索其他可能。</p>`);$$('[data-fate]').forEach(b=>b.onclick=()=>{if(chooseEnding(state,b.dataset.fate)){save();playCue('solve');showView('ending')}else toast('請先找回工程藍圖。');});}
function renderEnding(){const e=endings[state.ending];if(!e){showView('home');return}$('#ending-title').textContent=e.title;const art=document.querySelector('.ending-art');art.style.backgroundImage='linear-gradient(0deg,#110d13bf,transparent 65%),url(assets/endings/'+state.ending+'.svg)';art.setAttribute('role','img');art.setAttribute('aria-label','結局場景插畫：'+e.title);$('#ending-eyebrow').textContent=e.eyebrow;$('#ending-text').textContent=e.text;$('#ending-quote').textContent=e.quote;$('#ending-stats').innerHTML=`<span>旅程 ${formatTime(state.elapsed)}</span><span>真相 5 / 5</span><span>已發現結局 ${state.endings.length} / 3</span>`;renderHome();}
function openJournal(){const sections=rooms.map((r,i)=>{const list=r.spots.filter(s=>state.seen.includes(s.id));if(!list.length)return '';return list.map(s=>`<article class="journal-entry"><p class="eyebrow">${r.chapter} · ${r.title}</p><h3>${s.label}</h3><p>${s.text}</p></article>`).join('')}).join('');modal('被留下的真相','JOURNAL · 線索筆記',sections||'<p class="modal-text">筆記還是空白的。點擊場景中的光點，妳發現的線索會記錄在這裡。</p>');}
function openHint(){if(view!=='game'){toast('進入場景後即可查看提示。');return}const r=rooms[state.room];let count=state.hints[state.room]||0;const draw=()=>{modal('黑暗中的一點燭光','HINT · '+r.title,`<p class="modal-note">提示不會扣分，也不會改變結局。按照妳自己的步調探索。</p>${r.hints.slice(0,count).map((h,i)=>`<div class="hint-step"><span>0${i+1}</span><p>${h}</p></div>`).join('')}<button id="more-hint" class="primary-button" ${count===3?'disabled':''}>${count===0?'點亮第一道提示':count===3?'所有提示已展開':'展開更明確的提示'} ✧</button>`);$('#more-hint').onclick=()=>{count=Math.min(3,count+1);state.hints[state.room]=count;save();draw()};};draw();}
function openStory(){modal('當鏡子第一次說謊','PROLOGUE · 故事序章','<p class="modal-text">王后生下白雪公主的那一夜，王國有七十三個孩子死於寒冷。\n宮殿裡燃燒著七百支蠟燭。\n\n在霜棘王國，魔法不是奇蹟，而是一門生意。窮人，永遠是付錢的那一個。\n\n二十三年後，妳以艾薇・格雷的名字藏身黑鐘學院。午夜的鐘聲敲響第十三下。妳偷走一顆封著孩子記憶的玻璃心臟，卻發現自己也在王室的生命帳簿上。\n\n最高等級魔力容器。\n成年後可永久封存霜潮。\n\n最後一行，是妳父親的簽名。</p><p class="modal-note">改編自《白雪公主：血色魔鏡》。本作將主要事件重新編排為五幕密室探索；部分謎題與分支結局為遊戲原創。</p><button id="story-play" class="primary-button">開始妳的故事 ⟶</button>');$('#story-play').onclick=()=>{closeModal();if(state.started){state.ending?showView('ending'):showView('game')}else begin();};}
function openGuide(){modal('如何走出魔鏡','HOW TO PLAY · 遊玩指南','<ol class="guide-list"><li><strong>觀察場景。</strong>點擊帶有光暈的標記，閱讀文字。已看過的線索會有勾記。</li><li><strong>收取物品。</strong>在物品視窗按「收取」。只閱讀而沒有收取，物品不會進入背包。</li><li><strong>解開封印。</strong>比對線索，輸入密碼、排列符印或回答問題。沒有時間限制，也不會因答錯失去進度。</li><li><strong>需要幫助時。</strong>筆記會保留已探索的線索；提示會逐步揭露解法。</li><li><strong>決定代價。</strong>通過五幕後選擇結局。可回到最後的選擇，體驗另外兩種結局。</li></ol><p class="modal-note">手機與桌面皆使用點擊操作。進度自動儲存在目前瀏覽器，換裝置不會同步。音效預設關閉；開啟後建議配戴耳機。遊戲包含心理恐怖、死亡與生命剝削敘事，無閃光驚嚇。</p>');}
function begin(){resetChallenges();state={...initialState(),muted:state.muted,endings:state.endings};state.started=true;save();showView('game');modal('第十三聲鐘響','CHAPTER I · 黑鐘書庫',`<p class="modal-text">${rooms[0].intro}\n\n妳的第一個目標：找到禁書櫃的四位密碼。</p><p class="modal-note">點擊場景光點探索；收取道具後解開封印。進度會自動儲存。</p><button id="intro-explore" class="primary-button">開始探索 ⟶</button>`);$('#intro-explore').onclick=closeModal;}
function confirmReset(){modal('重新踏入魔鏡？','NEW JOURNEY · 新的旅程','<p class="modal-text">目前的章節進度、線索、物品與計時將重設。已發現的結局會保留。</p><button id="reset-confirm" class="primary-button">重新開始 ⟶</button><button id="reset-cancel" class="secondary-button">保留目前旅程</button>');$('#reset-confirm').onclick=()=>{closeModal();begin()};$('#reset-cancel').onclick=closeModal;}
function openSettings(){modal('讓黑暗更適合妳','SETTINGS · 遊戲設定',`<div class="settings-row"><span>場景配樂與音效</span><button id="setting-sound">${state.muted?'關閉':'開啟'}</button></div><div class="settings-row"><span>減少動畫</span><button id="setting-motion" aria-pressed="${document.body.classList.contains('reduce-motion')}">${document.body.classList.contains('reduce-motion')?'已開啟':'開啟'}</button></div><div class="settings-row"><span>儲存狀態</span><span>${saveFailed?'此瀏覽器無法儲存':'此裝置自動存檔'}</span></div><button id="setting-reset" class="secondary-button danger-button">重設本次旅程</button><p class="modal-note">存檔只儲存遊戲進度，不收集姓名、帳號或個人資料。關閉網頁後，下次可從首頁繼續。</p>`);$('#setting-sound').onclick=async()=>{await toggleSound();$('#setting-sound').textContent=state.muted?'關閉':'開啟'};$('#setting-motion').onclick=()=>{const enabled=document.body.classList.toggle('reduce-motion');$('#setting-motion').textContent=enabled?'已開啟':'開啟';$('#setting-motion').setAttribute('aria-pressed',String(enabled))};$('#setting-reset').onclick=confirmReset;}
function stopAudio(){soundtrack.stop();if(audio)audio.suspend().catch(()=>{});}
async function startAudio(){const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio)throw new Error('unsupported');if(!audio)audio=new Audio();await audio.resume();await soundtrack.start(currentTrack());}
async function toggleSound(){if(state.muted){try{await startAudio();state.muted=false;toast('環境音效已開啟')}catch{state.muted=true;toast('此瀏覽器目前無法播放音效。')}}else{state.muted=true;stopAudio()}updateSound();save();}
function updateSound(){$('#sound-icon').innerHTML=icon(state.muted?'mute':'sound');$('#sound').setAttribute('aria-pressed',String(!state.muted));$('#sound').setAttribute('aria-label',state.muted?'開啟環境音效':'關閉環境音效');$('.sound-label').textContent=state.muted?'音效關閉':'音效開啟';$('.settings-toggle').innerHTML=icon('gear');}
function playCue(kind){if(state.muted||!audio||audio.state!=='running')return;const notes=kind==='solve'?[220,329.63,440]:kind==='wrong'?[98,92]:kind==='collect'?[440,659.25]:[180];notes.forEach((f,i)=>{const o=audio.createOscillator(),g=audio.createGain(),t=audio.currentTime+i*.15;o.type='sine';o.frequency.value=f;g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(.06,t+.02);g.gain.exponentialRampToValueAtTime(.001,t+.45);o.connect(g);g.connect(audio.destination);o.start(t);o.stop(t+.5);o.onended=()=>{o.disconnect();g.disconnect()};});}
$('#sound').onclick=toggleSound;$('#start').onclick=()=>state.started?confirmReset():begin();$('#continue').onclick=()=>showView(state.ending?'ending':'game');$('.brand').onclick=e=>{e.preventDefault();showView('home')};$$('[data-action]').forEach(b=>b.onclick=()=>{const a=b.dataset.action;if(a==='home')showView('home');if(a==='guide')openGuide();if(a==='story')openStory();if(a==='journal')openJournal();if(a==='hint')openHint();if(a==='settings')openSettings();if(a==='chapters'){showView('home');$('#chapters').scrollIntoView({behavior:document.body.classList.contains('reduce-motion')?'instant':'smooth'});}if(a==='reconsider'){state.ending=null;state.room=4;save();showView('game');openFate();}});
setInterval(()=>{if(view==='game'&&!document.hidden&&state.started&&!state.ending){state.elapsed++;$('#timer').textContent=formatTime(state.elapsed);if(state.elapsed%10===0)save()}},1000);
document.addEventListener('visibilitychange',()=>{save();if(document.hidden)stopAudio();else if(!state.muted&&audio)startAudio().catch(()=>{})});window.addEventListener('pagehide',save);
// Audio must start in a user gesture. Restored progress always begins quietly.
state.muted=true;updateSound();renderHome();
