(function build(){
 const fs=require('node:fs'),path=require('node:path');
 const root=path.resolve(__dirname,'..'),catalog=JSON.parse(fs.readFileSync(path.join(root,'data/catalog.json'),'utf8'));
 const out=path.join(root,'dist');fs.rmSync(out,{recursive:true,force:true});fs.mkdirSync(path.join(out,'assets'),{recursive:true});
 for(const f of ['style.css','app.js'])fs.copyFileSync(path.join(root,'assets',f),path.join(out,'assets',f));
 const base=('/'+(process.env.BASE_PATH||'/').replace(/^\/+|\/+$/g,'')+'/').replace('//','/');
 const home=process.env.SITE_URL||'https://lucaslu3918.github.io/lucas-lab';
 const url=r=>base+r.replace(/^\/+/,'');const ext=String(home).replace(/\/+$/,'');
 const e=s=>String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');
 const navItems=[['tools/','工具'],['stories/','故事'],['games/','遊戲'],['projects/','作品'],['gallery/','藝廊'],['journal/','日誌']];
 const stateLabel=s=>({demo:'原創示範',pending:'劇本待匯入',concept:'概念規劃',live:'已公開',repo:'公開專案'})[s]||s;
 const view=(symbol,palette='blue')=>`<div class="visual ${e(palette)}" aria-hidden="true"><span>${e(symbol)}</span></div>`;
 const tag=(text)=>`<span class="status">${e(text)}</span>`;
 const card=(obj,kind)=>{
   const section={story:'stories',game:'games',project:'projects'}[kind]||kind;
   const href=url(section+'/'+obj.slug+'/');
   return `<article class="card" data-item data-category="${e(obj.category)}" data-index="${e([obj.title,obj.description,obj.category].join(' '))}">${view(obj.symbol,obj.palette)}<div class="body"><span class="label">${e(obj.category)}</span><h3><a href="${href}">${e(obj.title)}</a></h3><p>${e(obj.description)}</p><div class="bottom">${tag(stateLabel(obj.status))}<a class="action" href="${href}">查看詳情 ↗</a></div></div></article>`;
 };
 const toolCard=t=>`<article class="tool" data-item data-category="${e(t.category)}" data-index="${e([t.title,t.description,t.category,t.trait].join(' '))}"><div class="symbol" aria-hidden="true">${e(t.symbol)}</div><h3>${e(t.title)}</h3><p>${e(t.description)}</p><div class="bottom">${tag(t.trait)}<a class="action" href="${e(t.href)}" target="_blank" rel="noopener noreferrer" aria-label="${e('開啟 '+t.title+'（新分頁）')}">開啟原工具 ↗</a></div></article>`;
 const header=current=>`<a class="skip" href="#main">跳到主要內容</a><header class="header"><div class="wrap headerin"><a class="logo" href="${url('')}" aria-label="LUCAS LAB 首頁">LUCAS<b>✳</b>LAB</a><button class="menu" type="button" data-menu aria-controls="site-nav" aria-expanded="false" aria-label="開啟導覽選單">☰</button><nav id="site-nav" class="nav" aria-label="主要導覽"><a href="${url('')}" ${current==='home'?'aria-current="page"':''}>首頁</a>${navItems.map(([r,n])=>`<a href="${url(r)}" ${current===r.split('/')[0]?'aria-current="page"':''}>${n}</a>`).join('')}<a href="${url('about/')}" ${current==='about'?'aria-current="page"':''}>關於</a></nav><a class="github" href="https://github.com/LucasLu3918/lucas-lab" target="_blank" rel="noopener noreferrer">GitHub ↗</a></div></header>`;
 const footer=()=>`<footer class="footer"><div class="wrap footerin"><div><strong>LUCAS✳LAB</strong><br>Code · Create · Imagine<br><small>部分作品為規劃或閱讀展示，狀態均已明確標示。</small></div><div class="footlinks"><a href="${url('about/')}">關於我</a><a href="${url('search/')}">全站搜尋</a><a href="https://github.com/LucasLu3918" target="_blank" rel="noopener noreferrer">GitHub</a><a href="${url('legal/')}">內容與授權</a></div></div></footer>`;
 const page=(title,desc,current,html,route='',opts={})=>{
   const clean=route.replace(/^\/|\/$/g,'');const canonical=ext+'/'+(clean?clean+'/':'');
   const noindex=opts.noindex?'<meta name="robots" content="noindex,follow">':'<meta name="robots" content="index,follow">';
   return `<!doctype html><html lang="zh-Hant"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#090e18"><meta name="description" content="${e(desc)}">${noindex}<title>${e(title)}｜LUCAS LAB</title><link rel="canonical" href="${e(canonical)}"><meta property="og:type" content="website"><meta property="og:title" content="${e(title)}｜LUCAS LAB"><meta property="og:description" content="${e(desc)}"><meta property="og:url" content="${e(canonical)}"><link rel="stylesheet" href="${url('assets/style.css')}"><script src="${url('assets/app.js')}" defer></script></head><body>${header(current)}<main id="main">${html}</main>${footer()}</body></html>`;
 };
 const write=(route,html)=>{const dir=path.join(out,route);fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'index.html'),html,'utf8')};
 const intro=(eyebrow,title,desc)=>`<div class="wrap pageintro"><div class="eyebrow">${e(eyebrow)}</div><h1>${e(title)}</h1><p>${e(desc)}</p></div>`;
 const section=(eyebrow,title,desc,link,body)=>`<section class="section"><div class="wrap"><div class="sectionhead"><div><div class="eyebrow">${e(eyebrow)}</div><h2>${e(title)}</h2><p>${e(desc)}</p></div>${link?`<a class="more" href="${url(link)}">探索全部 ↗</a>`:''}</div>${body}</div></section>`;
 const library=(items,renderer,gridClass,options=true)=>`<div class="wrap" data-region>${options?`<div class="toolbar"><input class="search" type="search" data-search placeholder="搜尋名稱、分類或關鍵字" aria-label="搜尋作品"><div class="filters" aria-label="分類篩選"><button class="filter" type="button" data-filter="all" aria-pressed="true">全部</button>${[...new Set(items.map(x=>x.category))].map(cat=>`<button class="filter" type="button" data-filter="${e(cat)}" aria-pressed="false">${e(cat)}</button>`).join('')}</div></div>`:''}<p class="count" data-count aria-live="polite"></p><div class="${gridClass}">${items.map(renderer).join('')}</div><div class="empty" data-empty hidden>找不到符合條件的作品，請更換搜尋詞。</div></div>`;
 const cats=[['tools/','⚙','小工具館','實用工具與生活靈感'],['stories/','📖','故事藏書館','黑暗童話與原創奇幻'],['games/','🎮','互動遊戲館','選擇與探索的新體驗'],['projects/','◫','軟體作品集','產品設計與工程實踐'],['gallery/','✦','AI 視覺藝廊','角色與藝術探索'],['journal/','✎','創作與開發日誌','記錄背後的故事']];
 const categoryMarkup=cats.map(([route,s,title,desc])=>`<a class="cat" href="${url(route)}"><span class="symbol" aria-hidden="true">${s}</span><strong>${title} ↗</strong><span>${desc}</span></a>`).join('');
 const hero=`<section class="wrap hero"><div><div class="eyebrow">A CREATIVE DIGITAL PLAYGROUND</div><h1>CODE.<br>CREATE.<br><span class="gradient">IMAGINE.</span></h1><p>從一行程式，到一個奇幻世界。這裡收藏著工具、故事、遊戲與數位作品，每一個想法，都值得被實現。</p><div class="btnrow"><a class="btn primary" href="${url('search/')}">探索所有作品 ↗</a><a class="btn" href="${url('stories/')}">進入故事世界 →</a></div><p class="hero-note"><small>✳ AI-assisted creations &nbsp; · &nbsp; Made with imagination</small></p></div><div class="art" role="img" aria-label="紫色星球與青色軌道組成的奇幻宇宙插畫"><div class="planet"></div><div class="orbit"></div><div class="floatbadge a">⌘ CODE / BUILD</div><div class="floatbadge b">✦ WORLD / 01</div><div class="floatbadge c">◇ EXPLORE / PLAY</div><div class="artword">INFINITE POSSIBILITIES</div></div></section>`;
 const selected=[card(catalog.stories[0],'story'),card(catalog.stories[1],'story'),card(catalog.projects[0],'project')].join('');
 const feature=`<div class="feature">${view('✉','teal')}<div class="featurecopy"><div class="eyebrow">FEATURED STORY / READER DEMO</div><h2>霧林來信</h2><p>走進一座失去時間感的森林。兩章原創示範，支援閱讀模式、字體調整與章節切換。</p><a class="btn primary" href="${url('stories/mist-letters/')}">開始閱讀 →</a></div></div>`;
 const homeHtml=hero+section('DISCOVER THE UNIVERSE','探索創作宇宙','依照興趣開始探索六個不同的世界。',null,`<div class="cats">${categoryMarkup}</div>`)+section('SELECTED CREATIONS','精選創作','真實專案、原創示範與概念作品均明確標示。','search/',`<div class="cards">${selected}</div>`)+section('STORY SPOTLIGHT','走進故事世界','用更舒適的方式閱讀故事。','stories/',feature)+section('ORIGINAL TOOLS','實用工具，一鍵開啟','保留原 Lucas Tools 網站，不搬移程式碼。','tools/',`<div class="tools">${catalog.tools.slice(0,3).map(toolCard).join('')}</div>`)+`<section class="section"><div class="wrap callout"><div class="eyebrow">BEHIND THE SCENES</div><h2>不只是作品，更是創造的過程。</h2><p class="muted">查看產品規劃、技術實驗與 AI 創作背後的想法。</p><a class="btn" href="${url('journal/')}">前往開發日誌 ↗</a></div></section>`;
 write('',page('用程式實現想法，用 AI 創造世界','LUCAS LAB 個人 AI 創作平台：小工具、原創故事、互動遊戲、軟體作品與視覺藝廊。','home',homeHtml));
 write('tools',page('小工具館','探索 Lucas Tools 現有公開工具，直接開啟原網站使用。','tools',intro('TOOLS / OPEN ORIGINAL','實用工具，一鍵直達','工具由原本的 Lucas Tools 網站提供；本站只展示介紹與入口，不複製工具程式碼。')+`<div class="wrap"><div class="warning">外部工具會在新分頁開啟。部分工具需網路或第三方資料來源，實際可用狀態以原網站為準。</div></div>`+library(catalog.tools,toolCard,'tools')+`<div class="wrap section"><a class="btn primary" href="https://lucas-tools.owl3918.workers.dev/" target="_blank" rel="noopener noreferrer">前往完整 Lucas Tools 網站 ↗</a></div>`,'tools'));
 write('stories',page('故事藏書館','黑暗童話、奇幻故事與原創閱讀體驗。','stories',intro('STORY ARCHIVE','故事藏書館','每一段故事都有自己的世界。已完成的示範可閱讀，其餘作品待正式劇本匯入及內容審查。')+library(catalog.stories,s=>card(s,'story'),'cards'),'stories'));
 write('games',page('遊戲實驗室','互動文字冒險、解謎等遊戲概念展示。','games',intro('PLAYGROUND','互動遊戲館','遊戲尚在規劃中。這裡會逐步加入可直接遊玩的網頁遊戲與互動敘事。')+library(catalog.games,g=>card(g,'game'),'cards'),'games'));
 write('projects',page('軟體作品集','從產品設計到工程架構，探索開發專案。','projects',intro('SELECTED PROJECTS','軟體作品集','不只展示外觀，也記錄技術決策、問題背景、產品架構與開發成果。')+library(catalog.projects,p=>card(p,'project'),'cards'),'projects'));
 const galleryHtml=intro('VISUAL ARCHIVE','AI 視覺藝廊','角色、世界與幻想藝術的陳列空間。以下是風格佔位圖，不是已完成的 AI 插畫。')+`<section class="wrap section"><div class="gallery">${catalog.gallery.map((g,i)=>`<button type="button" data-preview data-palette="${e(g.palette)}" data-symbol="${e(g.symbol)}" data-title="${e(g.title)}" data-description="${e(g.description)}" aria-label="預覽 ${e(g.title)}">${view(g.symbol,g.palette)}<strong>${e(g.title)} · 概念</strong></button>`).join('')}</div><p class="muted">正式版將替換為擁有使用權的實際插畫與角色素材。</p></section><dialog class="dialog" id="gallery-dialog" aria-labelledby="gallery-dialog-title"><button type="button" class="close" data-dialog-close aria-label="關閉預覽">✕</button><div class="visual" data-dialog-visual><span></span></div><h2 data-dialog-title id="gallery-dialog-title"></h2><p data-dialog-desc class="muted"></p></dialog>`;
 write('gallery',page('AI 視覺藝廊','角色設計與奇幻視覺概念展示。','gallery',galleryHtml,'gallery'));
 const journalHtml=intro('BUILD LOG','開發與創作日誌','從產品設計、AI 輔助開發到創作實驗，記錄每一個階段。')+`<section class="wrap section"><div class="cards">${catalog.journal.map(j=>`<article class="card">${view('✎','blue')}<div class="body"><div class="label">${e(j.date)}</div><h3><a href="${url('journal/'+j.slug+'/')}">${e(j.title)}</a></h3><p>${e(j.description)}</p><div class="bottom"><a class="action" href="${url('journal/'+j.slug+'/')}">閱讀文章 ↗</a></div></div></article>`).join('')}</div></section>`;
 write('journal',page('開發日誌','LUCAS LAB 網站製作歷程與技術筆記。','journal',journalHtml,'journal'));
 write('journal/origin',page('LUCAS LAB：從工具到創作宇宙','LUCAS LAB 的網站緣起與設計規劃。','journal',`<div class="readerwrap"><div class="crumb"><a href="${url('journal/')}">日誌</a> / 2026-10-09</div><div class="eyebrow">THE BEGINNING</div><h1>LUCAS LAB：從工具到創作宇宙</h1><p class="muted">這個網站希望把實用工具、工程專案、故事劇本、遊戲與 AI 視覺創作整理成容易探索的空間。</p><h2>作品各自有個性，入口保持一致</h2><p>工具需要快速與好用，故事需要沉浸與舒適的閱讀，而工程作品需要清晰的背景、架構與成果說明。因此各個分區採不同呈現方式，並由共同的設計語言整合。</p><h2>先把基礎做好</h2><p>第一階段優先建立響應式網頁、可瀏覽的作品架構、公開工具入口，以及閱讀器示範。未來再逐步匯入經過審核的完整作品。</p><a class="btn" href="${url('')}" >返回首頁 →</a></div>`,'journal/origin'));
 write('about',page('關於這個創作平台','了解 LUCAS LAB 的創作理念與技術方向。','about',intro('ABOUT THE CREATOR','工程 × 創作 × 想像','透過軟體工程與 AI 輔助創作，探索從實用工具到互動敘事的各種可能。')+`<section class="wrap section"><div class="callout"><h2>用程式實現想法，用 AI 創造世界。</h2><p>這裡是個人作品展示與實驗空間：既有工具維持獨立運作，新的故事、遊戲與角色創作會持續整理。所有作品依實際狀態標示，不會把規劃當成已完成成果。</p><div class="btnrow"><a class="btn primary" href="https://github.com/LucasLu3918" target="_blank" rel="noopener noreferrer">查看 GitHub ↗</a><a class="btn" href="${url('projects/')}">瀏覽作品集 →</a></div></div></section>`,'about'));
 write('legal',page('內容、隱私與授權','網站的作品狀態、內容授權與隱私說明。','about',intro('POLICY','內容與授權說明','尊重創作內容、角色、圖片與程式碼權利。')+`<section class="wrap section"><h2>內容狀態</h2><p class="muted">示範作品為本站原創演示內容；尚未匯入或尚未經權利審查的劇本不提供正文。視覺圖形目前為 CSS 與符號概念佔位。</p><h2>原有工具</h2><p class="muted">Lucas Tools 由其原站獨立提供，使用工具時請依原站說明。本站不會代理或儲存工具輸入內容。</p><h2>隱私</h2><p class="muted">本站未加入第三方分析或會員系統。閱讀主題與文字大小可保存在此瀏覽器的 localStorage；清除網站資料即可移除。</p><h2>授權</h2><p class="muted">此網站原始碼授權依儲存庫授權文件為準；未另行標示的故事、視覺和品牌內容保留原作者權利。公開前應逐項確認第三方素材使用權。</p></section>`,'legal'));
 for(const s of catalog.stories){
   const ready=Array.isArray(s.chapters)&&s.chapters.length>0;
   const items=ready?s.chapters.map(c=>`<li><a href="${url('stories/'+s.slug+'/chapters/'+c.id+'/')}">${e(c.title)}<span>開始閱讀 ↗</span></a></li>`).join(''):'<li><span>章節內容待匯入與校稿<span>尚未開放</span></span></li>';
   const warning=s.warnings?.length?`<div class="warning">內容提示：${e(s.warnings.join('、'))}。此作品目前尚未開放章節內容。</div>`:'';
   const html=`<div class="wrap"><div class="crumb"><a href="${url('stories/')}">故事藏書館</a> / ${e(s.title)}</div><div class="detail"><div class="cover">${view(s.symbol,s.palette)}</div><div><div class="eyebrow">${e(s.subtitle)}</div><h1>${e(s.title)}</h1><p>${e(s.description)}</p><p class="label">狀態：${e(stateLabel(s.status))}</p>${warning}<h2>章節目錄</h2><ol class="chapterlist">${items}</ol>${ready?`<a class="btn primary" href="${url('stories/'+s.slug+'/chapters/'+s.chapters[0].id+'/')}">開始閱讀 →</a>`:`<a class="btn" href="${url('stories/')}">返回故事清單 →</a>`}</div></div></div>`;
   write('stories/'+s.slug,page(s.title,s.description,'stories',html,'stories/'+s.slug,{noindex:!ready}));
   if(!ready)continue;
   s.chapters.forEach((c,i)=>{
     const prev=s.chapters[i-1],next=s.chapters[i+1];
     const back=url('stories/'+s.slug+'/');
     const controls=`<div class="readerbar"><div><button type="button" data-theme="paper" aria-pressed="true">紙張</button> <button type="button" data-theme="night" aria-pressed="false">夜間</button></div><div class="reader-buttons"><button type="button" data-font="-1" aria-label="縮小字體">A−</button> <span data-size>18px</span> <button type="button" data-font="1" aria-label="放大字體">A＋</button></div></div>`;
     const content=`<div class="readerwrap"><div class="crumb"><a href="${url('stories/')}">故事藏書館</a> / <a href="${back}">${e(s.title)}</a> / ${e(c.title)}</div>${controls}<article class="readerpage" data-reader><div class="chaptermeta">LUCAS LAB · ORIGINAL DEMO</div><h1>${e(c.title)}</h1>${c.paragraphs.map(p=>`<p>${e(p)}</p>`).join('')}<p style="text-indent:0;text-align:center;font-size:13px;opacity:.6">— 本章完 —</p></article><nav class="chapternav" aria-label="章節導覽"><a class="btn" href="${prev?url('stories/'+s.slug+'/chapters/'+prev.id+'/'):back}">${prev?'← 上一章':'← 返回目錄'}</a><a class="btn primary" href="${next?url('stories/'+s.slug+'/chapters/'+next.id+'/'):back}">${next?'下一章 →':'返回目錄 →'}</a></nav></div>`;
     write('stories/'+s.slug+'/chapters/'+c.id,page(c.title+' — '+s.title,s.description,'stories',content,'stories/'+s.slug+'/chapters/'+c.id));
   });
 }
 for(const g of catalog.games){
   const html=`<div class="wrap"><div class="crumb"><a href="${url('games/')}">互動遊戲館</a> / ${e(g.title)}</div><div class="detail"><div class="cover">${view(g.symbol,g.palette)}</div><div><div class="eyebrow">${e(g.category)}</div><h1>${e(g.title)}</h1><p>${e(g.description)}</p><div class="warning">目前只有玩法規劃，尚無可遊玩版本，也未啟用存檔或成就。</div><h2>預計玩法</h2><p>以瀏覽器作為遊玩環境；正式完成後將提供觸控操作、鍵盤操作及進度保存。</p><a class="btn" href="${url('games/')}">返回遊戲清單 →</a></div></div></div>`;
   write('games/'+g.slug,page(g.title,g.description,'games',html,'games/'+g.slug,{noindex:true}));
 }
 for(const p of catalog.projects){
   const links=[p.href?`<a class="btn primary" href="${e(p.href)}" target="_blank" rel="noopener noreferrer">開啟${p.status==='live'?'原網站':'專案'} ↗</a>`:'',p.repo?`<a class="btn" href="${e(p.repo)}" target="_blank" rel="noopener noreferrer">GitHub 原始碼 ↗</a>`:''].join('');
   const html=`<div class="wrap"><div class="crumb"><a href="${url('projects/')}">軟體作品集</a> / ${e(p.title)}</div><div class="detail"><div class="cover">${view(p.symbol,p.palette)}</div><div><div class="eyebrow">${e(p.category)}</div><h1>${e(p.title)}</h1><p>${e(p.description)}</p><div class="label">狀態：${e(stateLabel(p.status))}</div><h2>作品重點</h2><ul>${p.highlights.map(x=>`<li>${e(x)}</li>`).join('')}</ul>${p.status==='concept'?'<div class="warning">此作品目前只是規劃概念，尚無公開可操作的 Demo。</div>':''}<div class="btnrow">${links||`<a class="btn" href="${url('projects/')}">返回作品清單 →</a>`}</div></div></div></div>`;
   write('projects/'+p.slug,page(p.title,p.description,'projects',html,'projects/'+p.slug,{noindex:p.status==='concept'}));
 }
 const searchable=[...catalog.stories.map(x=>({...x,kind:'story'})),...catalog.games.map(x=>({...x,kind:'game'})),...catalog.projects.map(x=>({...x,kind:'project'}))];
 const searchHtml=intro('ALL CREATIONS','全站作品搜尋','搜尋故事、遊戲、專案與工具。此版本提供本機即時篩選，不傳送搜尋內容至外部服務。')+library(searchable,x=>card(x,x.kind),'cards')+`<section class="wrap section"><h2>更多實用工具</h2><p class="muted">所有工具直接連至 Lucas Tools 原站。</p><div class="tools">${catalog.tools.slice(0,6).map(toolCard).join('')}</div></section>`;
 write('search',page('搜尋作品','搜尋故事、遊戲、工程作品與工具。','search',searchHtml,'search',{noindex:true}));
 fs.writeFileSync(path.join(out,'robots.txt'),`User-agent: *\nAllow: /\nSitemap: ${ext}/sitemap.xml\n`);
 const listed=['','tools','stories','games','projects','gallery','journal','journal/origin','about','legal','search',...catalog.stories.map(x=>'stories/'+x.slug),...catalog.projects.map(x=>'projects/'+x.slug),...catalog.games.map(x=>'games/'+x.slug)];
 fs.writeFileSync(path.join(out,'sitemap.xml'),'<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+listed.map(x=>`<url><loc>${e(ext+'/'+(x?x+'/':''))}</loc></url>`).join('')+'</urlset>');
 fs.writeFileSync(path.join(out,'404.html'),page('找不到頁面','此頁面不存在，請返回首頁。','',`<div class="wrap pageintro"><div class="eyebrow">404 / NOT FOUND</div><h1>這個世界暫時沒有入口。</h1><p>你尋找的頁面可能已被移動。</p><a class="btn primary" href="${url('')}">返回首頁 →</a></div>`,'404',{noindex:true}));
 console.log('Built '+listed.length+' routes + '+catalog.stories[0].chapters.length+' reader chapters into dist/');
})();
